### ISSUE TITLE
After deletion of a user, the number of leaders is not automatically replenished to four, even if other users are in the movement.

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-server#40]
I signalled in the 'clean teeth' movement, in which I had three leaders at that time, after the deletion of Pieter's double. After refreshing the page, I still had three leaders, which implied to me that there were no others in the movement. However, after signalling, I switched out Marick and got Diederik back as new leader (immediately). This tells me that there were other people in the movement, even though timeline only showed me three. Also, refreshing the page does not give me back either Marick or another fourth leader. So my leaders are not automatically 'refilled' to four.

**Comment by Drvanon** [comment]
We are currently rewriting the way users in movements work, so this will be fixed in that system.

**Comment by PJvanVliet** [comment]
@Drvanon, this should be solved by #47.

**Comment by Drvanon** [comment]
Correct!
