### ISSUE TITLE
The client should be able to obtain the username from the server

### ISSUE THREAD

**Issue by Yori-O92** [GridtNetwork/gridt-server#44]

**Comment by Drvanon** [comment]
Endpoint should be called "/identity", it should give the information:
* bio
* username
* avatar

**Comment by marickmanrho** [comment]
Should also give
- User ID

**Comment by Drvanon** [comment]
> Endpoint should be called "/identity", it should give the information:
> 
> * bio
> * username
> * avatar

Should have been email adress instead of avatar
