### ISSUE TITLE
As an authorized user I want to be able to change my email.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-server#51]
I should be able to supply my password with this as well, to make sure that I know what I am doing.

**Comment by PJvanVliet** [comment]
1. Create a new resource (ChangeEmailResource) (web/gridt/resources/user.py)
- Validate input (similarly to web/gridt/resources/movements.py:27)
- Required input (web/gridt/schemas.py): old password, new e-mail
- Validate password using user.verify_password(pass)
- Change e-mail (avatar will automatically be updated)
2. Register new resource in app (web/app.py:93)
3. Register new endpoint in openapi (web/docs/_static/openapi.yaml:11)

**Comment by PJvanVliet** [comment]
Closed by #54
