### ISSUE TITLE
As an authorized user I want to be able to change my password.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-server#52]
I should only be allowed to do this when I can recount my old password. An email should be sent to my account when this is done.

**Comment by Drvanon** [comment]
1. Create new resource (web/gridt/resources/user.py)
  - Required input: old password (web/gridt/schemas.py)
  - Validate input (similarly to web/gridt/resources/movements.py:27)
  - Validate password user.verify_password(pass)
  - Change actual password using user.hash_password(password)
2. Register new resource in app (web/gridt/app.py:93)

**Comment by PJvanVliet** [comment]
Should still implement and test the e-mail function belonging to a password change.

**Comment by PJvanVliet** [comment]
Closed by #53
